version: '3.3'
services: 
  web_tecgraf:
    image: "mcr.microsoft.com/dotnet/sdk:3.1"
    container_name: web_tecgraf 
    volumes:
      - ./src:/app  
    command: dotnet restore /app/Web
    command: dotnet build /app/Web 
    command: dotnet run --project /app/Web run --urls "http://0.0.0.0:4002"   
    ports:
      - "4002:4002" 

volumes:
  db_data: {}